// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckConnection() {
  return window['go']['main']['App']['CheckConnection']();
}

export function CreateSession() {
  return window['go']['main']['App']['CreateSession']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function IsTerminalActive() {
  return window['go']['main']['App']['IsTerminalActive']();
}

export function ResizeTerminal(arg1, arg2) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SendMessageWithModel(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessageWithModel'](arg1, arg2, arg3);
}

export function SetServerURL(arg1) {
  return window['go']['main']['App']['SetServerURL'](arg1);
}

export function StartTerminal() {
  return window['go']['main']['App']['StartTerminal']();
}

export function StopTerminal() {
  return window['go']['main']['App']['StopTerminal']();
}

export function SubscribeEvents() {
  return window['go']['main']['App']['SubscribeEvents']();
}

export function WriteTerminal(arg1) {
  return window['go']['main']['App']['WriteTerminal'](arg1);
}
