// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddKiroAccount(arg1, arg2) {
  return window['go']['main']['App']['AddKiroAccount'](arg1, arg2);
}

export function AddMCPServer(arg1, arg2) {
  return window['go']['main']['App']['AddMCPServer'](arg1, arg2);
}

export function AddTag(arg1) {
  return window['go']['main']['App']['AddTag'](arg1);
}

export function AuthenticateKiro() {
  return window['go']['main']['App']['AuthenticateKiro']();
}

export function AutoStartOpenCode() {
  return window['go']['main']['App']['AutoStartOpenCode']();
}

export function BatchAddKiroTags(arg1, arg2) {
  return window['go']['main']['App']['BatchAddKiroTags'](arg1, arg2);
}

export function BatchDeleteKiroAccounts(arg1) {
  return window['go']['main']['App']['BatchDeleteKiroAccounts'](arg1);
}

export function BatchRefreshKiroQuota(arg1) {
  return window['go']['main']['App']['BatchRefreshKiroQuota'](arg1);
}

export function BatchRefreshKiroTokens(arg1) {
  return window['go']['main']['App']['BatchRefreshKiroTokens'](arg1);
}

export function CancelSession(arg1) {
  return window['go']['main']['App']['CancelSession'](arg1);
}

export function CheckConnection() {
  return window['go']['main']['App']['CheckConnection']();
}

export function CleanupTempFiles() {
  return window['go']['main']['App']['CleanupTempFiles']();
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CodeCompletion(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CodeCompletion'](arg1, arg2, arg3, arg4);
}

export function CompleteKiroOAuthWithURL(arg1) {
  return window['go']['main']['App']['CompleteKiroOAuthWithURL'](arg1);
}

export function ConnectMCPServer(arg1) {
  return window['go']['main']['App']['ConnectMCPServer'](arg1);
}

export function CopyPath(arg1, arg2) {
  return window['go']['main']['App']['CopyPath'](arg1, arg2);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function CreateNewFile(arg1, arg2) {
  return window['go']['main']['App']['CreateNewFile'](arg1, arg2);
}

export function CreateNewFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateNewFolder'](arg1, arg2);
}

export function CreateSession() {
  return window['go']['main']['App']['CreateSession']();
}

export function CreateSkill(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateSkill'](arg1, arg2, arg3, arg4);
}

export function CreateSkillFromTemplate(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSkillFromTemplate'](arg1, arg2, arg3);
}

export function CreateTerminal() {
  return window['go']['main']['App']['CreateTerminal']();
}

export function DeletePath(arg1) {
  return window['go']['main']['App']['DeletePath'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DisconnectMCPServer(arg1) {
  return window['go']['main']['App']['DisconnectMCPServer'](arg1);
}

export function ExportKiroAccounts(arg1) {
  return window['go']['main']['App']['ExportKiroAccounts'](arg1);
}

export function FixOhMyOpenCode() {
  return window['go']['main']['App']['FixOhMyOpenCode']();
}

export function GetAccountSettings() {
  return window['go']['main']['App']['GetAccountSettings']();
}

export function GetActiveKiroAccount() {
  return window['go']['main']['App']['GetActiveKiroAccount']();
}

export function GetAllModels() {
  return window['go']['main']['App']['GetAllModels']();
}

export function GetAntigravityAuthStatus() {
  return window['go']['main']['App']['GetAntigravityAuthStatus']();
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigModels() {
  return window['go']['main']['App']['GetConfigModels']();
}

export function GetConfigPaths() {
  return window['go']['main']['App']['GetConfigPaths']();
}

export function GetGitStatus(arg1) {
  return window['go']['main']['App']['GetGitStatus'](arg1);
}

export function GetKiroAccountStats() {
  return window['go']['main']['App']['GetKiroAccountStats']();
}

export function GetKiroAccounts() {
  return window['go']['main']['App']['GetKiroAccounts']();
}

export function GetKiroAuthStatus() {
  return window['go']['main']['App']['GetKiroAuthStatus']();
}

export function GetKiroQuota(arg1) {
  return window['go']['main']['App']['GetKiroQuota'](arg1);
}

export function GetMCPConfig() {
  return window['go']['main']['App']['GetMCPConfig']();
}

export function GetMCPConfigPath() {
  return window['go']['main']['App']['GetMCPConfigPath']();
}

export function GetMCPMarket() {
  return window['go']['main']['App']['GetMCPMarket']();
}

export function GetMCPStatus() {
  return window['go']['main']['App']['GetMCPStatus']();
}

export function GetMCPTools() {
  return window['go']['main']['App']['GetMCPTools']();
}

export function GetMCPToolsPrompt() {
  return window['go']['main']['App']['GetMCPToolsPrompt']();
}

export function GetOhMyOpenCodeStatus() {
  return window['go']['main']['App']['GetOhMyOpenCodeStatus']();
}

export function GetOpenCodeStatus() {
  return window['go']['main']['App']['GetOpenCodeStatus']();
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetQuotaAlerts() {
  return window['go']['main']['App']['GetQuotaAlerts']();
}

export function GetRemoteControlInfo() {
  return window['go']['main']['App']['GetRemoteControlInfo']();
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function GetSessionMessages(arg1) {
  return window['go']['main']['App']['GetSessionMessages'](arg1);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetSkill(arg1) {
  return window['go']['main']['App']['GetSkill'](arg1);
}

export function GetSkillTemplates() {
  return window['go']['main']['App']['GetSkillTemplates']();
}

export function GetSkills() {
  return window['go']['main']['App']['GetSkills']();
}

export function GetStorageInfo() {
  return window['go']['main']['App']['GetStorageInfo']();
}

export function GetSystemMachineID() {
  return window['go']['main']['App']['GetSystemMachineID']();
}

export function GetTags() {
  return window['go']['main']['App']['GetTags']();
}

export function GetTerminals() {
  return window['go']['main']['App']['GetTerminals']();
}

export function GetUIUXProMaxStatus() {
  return window['go']['main']['App']['GetUIUXProMaxStatus']();
}

export function GetWorkDir() {
  return window['go']['main']['App']['GetWorkDir']();
}

export function GitAdd(arg1, arg2) {
  return window['go']['main']['App']['GitAdd'](arg1, arg2);
}

export function GitCommit(arg1, arg2) {
  return window['go']['main']['App']['GitCommit'](arg1, arg2);
}

export function GitDiscard(arg1, arg2) {
  return window['go']['main']['App']['GitDiscard'](arg1, arg2);
}

export function GitPull(arg1) {
  return window['go']['main']['App']['GitPull'](arg1);
}

export function GitPush(arg1) {
  return window['go']['main']['App']['GitPush'](arg1);
}

export function HandleKiroOAuthCallback(arg1, arg2) {
  return window['go']['main']['App']['HandleKiroOAuthCallback'](arg1, arg2);
}

export function ImportKiroAccounts(arg1, arg2) {
  return window['go']['main']['App']['ImportKiroAccounts'](arg1, arg2);
}

export function InstallAntigravityAuth() {
  return window['go']['main']['App']['InstallAntigravityAuth']();
}

export function InstallKiroAuth() {
  return window['go']['main']['App']['InstallKiroAuth']();
}

export function InstallOhMyOpenCode() {
  return window['go']['main']['App']['InstallOhMyOpenCode']();
}

export function InstallOpenCode() {
  return window['go']['main']['App']['InstallOpenCode']();
}

export function InstallUIUXProMax() {
  return window['go']['main']['App']['InstallUIUXProMax']();
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function LogToTerminal(arg1) {
  return window['go']['main']['App']['LogToTerminal'](arg1);
}

export function MovePath(arg1, arg2) {
  return window['go']['main']['App']['MovePath'](arg1, arg2);
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function OpenInFinder(arg1) {
  return window['go']['main']['App']['OpenInFinder'](arg1);
}

export function OpenMCPConfigFile() {
  return window['go']['main']['App']['OpenMCPConfigFile']();
}

export function ReadFileContent(arg1) {
  return window['go']['main']['App']['ReadFileContent'](arg1);
}

export function RefreshActiveKiroQuota() {
  return window['go']['main']['App']['RefreshActiveKiroQuota']();
}

export function RefreshKiroQuota(arg1) {
  return window['go']['main']['App']['RefreshKiroQuota'](arg1);
}

export function RefreshKiroToken(arg1) {
  return window['go']['main']['App']['RefreshKiroToken'](arg1);
}

export function RemoveKiroAccount(arg1) {
  return window['go']['main']['App']['RemoveKiroAccount'](arg1);
}

export function RemoveMCPServer(arg1) {
  return window['go']['main']['App']['RemoveMCPServer'](arg1);
}

export function RenamePath(arg1, arg2) {
  return window['go']['main']['App']['RenamePath'](arg1, arg2);
}

export function ReplaceInFiles(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReplaceInFiles'](arg1, arg2, arg3, arg4);
}

export function ResetConfiguration() {
  return window['go']['main']['App']['ResetConfiguration']();
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RestartOpenCode() {
  return window['go']['main']['App']['RestartOpenCode']();
}

export function RunFile(arg1) {
  return window['go']['main']['App']['RunFile'](arg1);
}

export function SaveImageToWorkDir(arg1) {
  return window['go']['main']['App']['SaveImageToWorkDir'](arg1);
}

export function SaveMCPConfig(arg1) {
  return window['go']['main']['App']['SaveMCPConfig'](arg1);
}

export function SearchInFiles(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchInFiles'](arg1, arg2, arg3, arg4);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SendMessageWithModel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendMessageWithModel'](arg1, arg2, arg3, arg4);
}

export function SetActiveFile(arg1, arg2) {
  return window['go']['main']['App']['SetActiveFile'](arg1, arg2);
}

export function SetOpenCodeWorkDir(arg1) {
  return window['go']['main']['App']['SetOpenCodeWorkDir'](arg1);
}

export function SetServerURL(arg1) {
  return window['go']['main']['App']['SetServerURL'](arg1);
}

export function SetWorkDir(arg1) {
  return window['go']['main']['App']['SetWorkDir'](arg1);
}

export function StartKiroOAuth(arg1) {
  return window['go']['main']['App']['StartKiroOAuth'](arg1);
}

export function StartOpenCode() {
  return window['go']['main']['App']['StartOpenCode']();
}

export function StartRemoteControl(arg1) {
  return window['go']['main']['App']['StartRemoteControl'](arg1);
}

export function StopOpenCode() {
  return window['go']['main']['App']['StopOpenCode']();
}

export function StopRemoteControl() {
  return window['go']['main']['App']['StopRemoteControl']();
}

export function SubscribeEvents() {
  return window['go']['main']['App']['SubscribeEvents']();
}

export function SwitchKiroAccount(arg1) {
  return window['go']['main']['App']['SwitchKiroAccount'](arg1);
}

export function ToggleMCPServer(arg1, arg2) {
  return window['go']['main']['App']['ToggleMCPServer'](arg1, arg2);
}

export function UninstallAntigravityAuth() {
  return window['go']['main']['App']['UninstallAntigravityAuth']();
}

export function UninstallKiroAuth() {
  return window['go']['main']['App']['UninstallKiroAuth']();
}

export function UninstallOhMyOpenCode() {
  return window['go']['main']['App']['UninstallOhMyOpenCode']();
}

export function UninstallUIUXProMax() {
  return window['go']['main']['App']['UninstallUIUXProMax']();
}

export function UnwatchFile(arg1) {
  return window['go']['main']['App']['UnwatchFile'](arg1);
}

export function UpdateAccountSettings(arg1) {
  return window['go']['main']['App']['UpdateAccountSettings'](arg1);
}

export function UpdateAntigravityAuth() {
  return window['go']['main']['App']['UpdateAntigravityAuth']();
}

export function UpdateAppConfig(arg1) {
  return window['go']['main']['App']['UpdateAppConfig'](arg1);
}

export function UpdateKiroAccount(arg1, arg2) {
  return window['go']['main']['App']['UpdateKiroAccount'](arg1, arg2);
}

export function UpdateKiroAuth() {
  return window['go']['main']['App']['UpdateKiroAuth']();
}

export function UpdateSkill(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSkill'](arg1, arg2, arg3);
}

export function UpdateUIUXProMax() {
  return window['go']['main']['App']['UpdateUIUXProMax']();
}

export function ValidateConfiguration() {
  return window['go']['main']['App']['ValidateConfiguration']();
}

export function ValidateKiroToken(arg1) {
  return window['go']['main']['App']['ValidateKiroToken'](arg1);
}

export function WatchFile(arg1) {
  return window['go']['main']['App']['WatchFile'](arg1);
}

export function WriteFileContent(arg1, arg2) {
  return window['go']['main']['App']['WriteFileContent'](arg1, arg2);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}
