// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckConnection():Promise<boolean>;

export function CreateSession():Promise<main.Session>;

export function GetConfig():Promise<main.ConfigInfo>;

export function GetProviders():Promise<main.ProviderInfo>;

export function GetServerURL():Promise<string>;

export function GetSessions():Promise<Array<main.Session>>;

export function IsTerminalActive():Promise<boolean>;

export function ResizeTerminal(arg1:number,arg2:number):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function SendMessageWithModel(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetServerURL(arg1:string):Promise<void>;

export function StartTerminal():Promise<void>;

export function StopTerminal():Promise<void>;

export function SubscribeEvents():Promise<void>;

export function WriteTerminal(arg1:string):Promise<void>;
