// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMCPServer(arg1, arg2) {
  return window['go']['main']['App']['AddMCPServer'](arg1, arg2);
}

export function AuthenticateKiro() {
  return window['go']['main']['App']['AuthenticateKiro']();
}

export function AutoStartOpenCode() {
  return window['go']['main']['App']['AutoStartOpenCode']();
}

export function CancelSession(arg1) {
  return window['go']['main']['App']['CancelSession'](arg1);
}

export function CheckConnection() {
  return window['go']['main']['App']['CheckConnection']();
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CodeCompletion(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CodeCompletion'](arg1, arg2, arg3, arg4);
}

export function ConnectMCPServer(arg1) {
  return window['go']['main']['App']['ConnectMCPServer'](arg1);
}

export function CopyPath(arg1, arg2) {
  return window['go']['main']['App']['CopyPath'](arg1, arg2);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function CreateNewFile(arg1, arg2) {
  return window['go']['main']['App']['CreateNewFile'](arg1, arg2);
}

export function CreateNewFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateNewFolder'](arg1, arg2);
}

export function CreateSession() {
  return window['go']['main']['App']['CreateSession']();
}

export function CreateTerminal() {
  return window['go']['main']['App']['CreateTerminal']();
}

export function DeletePath(arg1) {
  return window['go']['main']['App']['DeletePath'](arg1);
}

export function DisconnectMCPServer(arg1) {
  return window['go']['main']['App']['DisconnectMCPServer'](arg1);
}

export function FixOhMyOpenCode() {
  return window['go']['main']['App']['FixOhMyOpenCode']();
}

export function GetAntigravityAuthStatus() {
  return window['go']['main']['App']['GetAntigravityAuthStatus']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigModels() {
  return window['go']['main']['App']['GetConfigModels']();
}

export function GetGitStatus(arg1) {
  return window['go']['main']['App']['GetGitStatus'](arg1);
}

export function GetKiroAuthStatus() {
  return window['go']['main']['App']['GetKiroAuthStatus']();
}

export function GetMCPConfig() {
  return window['go']['main']['App']['GetMCPConfig']();
}

export function GetMCPConfigPath() {
  return window['go']['main']['App']['GetMCPConfigPath']();
}

export function GetMCPMarket() {
  return window['go']['main']['App']['GetMCPMarket']();
}

export function GetMCPStatus() {
  return window['go']['main']['App']['GetMCPStatus']();
}

export function GetMCPTools() {
  return window['go']['main']['App']['GetMCPTools']();
}

export function GetMCPToolsPrompt() {
  return window['go']['main']['App']['GetMCPToolsPrompt']();
}

export function GetOhMyOpenCodeStatus() {
  return window['go']['main']['App']['GetOhMyOpenCodeStatus']();
}

export function GetOpenCodeStatus() {
  return window['go']['main']['App']['GetOpenCodeStatus']();
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function GetSessionMessages(arg1) {
  return window['go']['main']['App']['GetSessionMessages'](arg1);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetTerminals() {
  return window['go']['main']['App']['GetTerminals']();
}

export function GetWorkDir() {
  return window['go']['main']['App']['GetWorkDir']();
}

export function GitAdd(arg1, arg2) {
  return window['go']['main']['App']['GitAdd'](arg1, arg2);
}

export function GitCommit(arg1, arg2) {
  return window['go']['main']['App']['GitCommit'](arg1, arg2);
}

export function GitDiscard(arg1, arg2) {
  return window['go']['main']['App']['GitDiscard'](arg1, arg2);
}

export function GitPull(arg1) {
  return window['go']['main']['App']['GitPull'](arg1);
}

export function GitPush(arg1) {
  return window['go']['main']['App']['GitPush'](arg1);
}

export function InstallAntigravityAuth() {
  return window['go']['main']['App']['InstallAntigravityAuth']();
}

export function InstallKiroAuth() {
  return window['go']['main']['App']['InstallKiroAuth']();
}

export function InstallOhMyOpenCode() {
  return window['go']['main']['App']['InstallOhMyOpenCode']();
}

export function InstallOpenCode() {
  return window['go']['main']['App']['InstallOpenCode']();
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function MovePath(arg1, arg2) {
  return window['go']['main']['App']['MovePath'](arg1, arg2);
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function OpenInFinder(arg1) {
  return window['go']['main']['App']['OpenInFinder'](arg1);
}

export function OpenKiroAuthManual() {
  return window['go']['main']['App']['OpenKiroAuthManual']();
}

export function OpenMCPConfigFile() {
  return window['go']['main']['App']['OpenMCPConfigFile']();
}

export function ReadFileContent(arg1) {
  return window['go']['main']['App']['ReadFileContent'](arg1);
}

export function RemoveMCPServer(arg1) {
  return window['go']['main']['App']['RemoveMCPServer'](arg1);
}

export function RenamePath(arg1, arg2) {
  return window['go']['main']['App']['RenamePath'](arg1, arg2);
}

export function ReplaceInFiles(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReplaceInFiles'](arg1, arg2, arg3, arg4);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RestartOpenCode() {
  return window['go']['main']['App']['RestartOpenCode']();
}

export function RunFile(arg1) {
  return window['go']['main']['App']['RunFile'](arg1);
}

export function SaveImageToWorkDir(arg1) {
  return window['go']['main']['App']['SaveImageToWorkDir'](arg1);
}

export function SaveMCPConfig(arg1) {
  return window['go']['main']['App']['SaveMCPConfig'](arg1);
}

export function SearchInFiles(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchInFiles'](arg1, arg2, arg3, arg4);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SendMessageWithModel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendMessageWithModel'](arg1, arg2, arg3, arg4);
}

export function SetActiveFile(arg1, arg2) {
  return window['go']['main']['App']['SetActiveFile'](arg1, arg2);
}

export function SetOpenCodeWorkDir(arg1) {
  return window['go']['main']['App']['SetOpenCodeWorkDir'](arg1);
}

export function SetServerURL(arg1) {
  return window['go']['main']['App']['SetServerURL'](arg1);
}

export function SetWorkDir(arg1) {
  return window['go']['main']['App']['SetWorkDir'](arg1);
}

export function StartOpenCode() {
  return window['go']['main']['App']['StartOpenCode']();
}

export function StopOpenCode() {
  return window['go']['main']['App']['StopOpenCode']();
}

export function SubscribeEvents() {
  return window['go']['main']['App']['SubscribeEvents']();
}

export function ToggleMCPServer(arg1, arg2) {
  return window['go']['main']['App']['ToggleMCPServer'](arg1, arg2);
}

export function UninstallAntigravityAuth() {
  return window['go']['main']['App']['UninstallAntigravityAuth']();
}

export function UninstallKiroAuth() {
  return window['go']['main']['App']['UninstallKiroAuth']();
}

export function UninstallOhMyOpenCode() {
  return window['go']['main']['App']['UninstallOhMyOpenCode']();
}

export function UnwatchFile(arg1) {
  return window['go']['main']['App']['UnwatchFile'](arg1);
}

export function WatchFile(arg1) {
  return window['go']['main']['App']['WatchFile'](arg1);
}

export function WriteFileContent(arg1, arg2) {
  return window['go']['main']['App']['WriteFileContent'](arg1, arg2);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}
