// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddMCPServer(arg1:string,arg2:main.MCPServer):Promise<Record<string, main.MCPServerStatus>>;

export function AutoStartOpenCode():Promise<void>;

export function CancelSession(arg1:string):Promise<void>;

export function CheckConnection():Promise<boolean>;

export function CloseTerminal(arg1:number):Promise<void>;

export function CodeCompletion(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ConnectMCPServer(arg1:string):Promise<void>;

export function CreateSession():Promise<main.Session>;

export function CreateTerminal():Promise<number>;

export function DisconnectMCPServer(arg1:string):Promise<void>;

export function GetConfig():Promise<main.ConfigInfo>;

export function GetMCPConfig():Promise<main.MCPConfig>;

export function GetMCPConfigPath():Promise<string>;

export function GetMCPMarket():Promise<Array<main.MCPMarketItem>>;

export function GetMCPStatus():Promise<Record<string, main.MCPServerStatus>>;

export function GetMCPTools():Promise<Array<main.MCPTool>>;

export function GetMCPToolsPrompt():Promise<string>;

export function GetOpenCodeStatus():Promise<main.OpenCodeStatus>;

export function GetProviders():Promise<main.ProviderInfo>;

export function GetServerURL():Promise<string>;

export function GetSessionMessages(arg1:string):Promise<Array<main.Message>>;

export function GetSessions():Promise<Array<main.Session>>;

export function GetTerminals():Promise<Array<number>>;

export function GetWorkDir():Promise<string>;

export function InstallOpenCode():Promise<void>;

export function ListDir(arg1:string):Promise<Array<main.FileInfo>>;

export function OpenFolder():Promise<string>;

export function OpenMCPConfigFile():Promise<string>;

export function ReadFileContent(arg1:string):Promise<string>;

export function RemoveMCPServer(arg1:string):Promise<void>;

export function ResizeTerminal(arg1:number,arg2:number,arg3:number):Promise<void>;

export function RunFile(arg1:string):Promise<string>;

export function SaveImageToWorkDir(arg1:main.ImageData):Promise<string>;

export function SaveMCPConfig(arg1:main.MCPConfig):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function SendMessageWithModel(arg1:string,arg2:string,arg3:string,arg4:Array<main.ImageData>):Promise<void>;

export function SetActiveFile(arg1:string,arg2:string):Promise<void>;

export function SetOpenCodeWorkDir(arg1:string):Promise<void>;

export function SetServerURL(arg1:string):Promise<void>;

export function SetWorkDir(arg1:string):Promise<void>;

export function StartOpenCode():Promise<void>;

export function StopOpenCode():Promise<void>;

export function SubscribeEvents():Promise<void>;

export function ToggleMCPServer(arg1:string,arg2:boolean):Promise<void>;

export function UnwatchFile(arg1:string):Promise<void>;

export function WatchFile(arg1:string):Promise<void>;

export function WriteFileContent(arg1:string,arg2:string):Promise<void>;

export function WriteTerminal(arg1:number,arg2:string):Promise<void>;
