// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AutoStartOpenCode():Promise<void>;

export function CheckConnection():Promise<boolean>;

export function CloseTerminal(arg1:number):Promise<void>;

export function CreateSession():Promise<main.Session>;

export function CreateTerminal():Promise<number>;

export function GetConfig():Promise<main.ConfigInfo>;

export function GetOpenCodeStatus():Promise<main.OpenCodeStatus>;

export function GetProviders():Promise<main.ProviderInfo>;

export function GetServerURL():Promise<string>;

export function GetSessions():Promise<Array<main.Session>>;

export function GetTerminals():Promise<Array<number>>;

export function InstallOpenCode():Promise<void>;

export function ResizeTerminal(arg1:number,arg2:number,arg3:number):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function SendMessageWithModel(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetServerURL(arg1:string):Promise<void>;

export function StartOpenCode():Promise<void>;

export function StopOpenCode():Promise<void>;

export function SubscribeEvents():Promise<void>;

export function WriteTerminal(arg1:number,arg2:string):Promise<void>;
